### ISSUE TITLE
Correctly parse Destinations with Certificates

### ISSUE THREAD

**Issue by nolaforensix** [i2p/libsam3#5]
libsam3.h contains the following definition:

#define SAM3_PUBKEY_SIZE   (516)

sam3NameLookup insists that the size of the public key returned via sam3FindField is equal to SAM3_PUBKEY_SIZE (516) while some results returned are larger than this.

Specifically, the base64 public key returned for  zzz.i2p is:

```
GKapJ8koUcBj~jmQzHsTYxDg2tpfWj0xjQTzd8BhfC9c3OS5fwPBNajgF-eOD6eCjFTqTlorlh7Hnd8kXj1qblUGXT-tDoR9~YV8dmXl51cJn9MVTRrEqRWSJVXbUUz9t5Po6Xa247Vr0sJn27R4KoKP8QVj1GuH6dB3b6wTPbOamC3dkO18vkQkfZWUdRMDXk0d8AdjB0E0864nOT~J9Fpnd2pQE5uoFT6P0DqtQR2jsFvf9ME61aqLvKPPWpkgdn4z6Zkm-NJOcDz2Nv8Si7hli94E9SghMYRsdjU-knObKvxiagn84FIwcOpepxuG~kFXdD5NfsH0v6Uri3usE3XWD7Pw6P8qVYF39jUIq4OiNMwPnNYzy2N4mDMQdsdHO3LUVh~DEppOy9AAmEoHDjjJxt2BFBbGxfdpZCpENkwvmZeYUyNCCzASqTOOlNzdpne8cuesn3NDXIpNnqEE6Oe5Qm5YOJykrX~Vx~cFFT3QzDGkIjjxlFBsjUJyYkFjBQAEAAcAAA==
```

This value is the correct value from the router's address book and is 524 bytes long.  A base32 conversion of this value also yields the correct b32 value in the router's address book:  

```
lhbd7ojcaiofbfku7ixh47qj537g572zmhdc4oilvugzxdpdghua.b32.i2p
```

Is this a case where perhaps the libsam function should be a little more forgiving, rather than throwing errors?

**Comment by str4d** [comment]
The problem is that the library was written when Destinations only supported one signature type, and were always 516 bytes with the default empty certificate. What it should be doing instead is parsing the Destination completely, including the variable-length certificate at the end. Then it would be able to transparently handle the newer signature types for remote Destinations.

The simplest way to support this would be to increase the size of the fixed-length array to encompass all current signature types, and then store the actual length of the Destination separately.

Actually supporting new signature types for the user's own destinations will be implemented as part of #1.
